name: github_blog CI/CD

on:
  push:
    branches: [master]
    paths:
      - "src/acmicpc/*"
      - "src/leetcode/*"


jobs:
  cicd:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Generate docs
        run: |
          python3 docs/build_md.py
      - name: Checkout blog repo
        uses: actions/checkout@v2
        with:
          repository: Aiden-Jeon/Aiden-Jeon.github.io
          token: ${{ secrets.CR_PAT }}
          path: blog
      - name: Copy
        run: |
          cp -r docs/algorithm blog/content/post
      - name: Commit file
        run: |
          cd blog
          git config --local user.email "aiden.jongseob@gmail.com"
          git config --local user.name "Aiden-Jeon"
          git add ./content/post/algorithm
          git diff --quiet && git diff --staged --quiet || git commit -m "Update algorithm post"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: blog
          repository: Aiden-Jeon/Aiden-Jeon.github.io
          github_token: ${{ secrets.CR_PAT }}
          branch: main
